name: Continuous Integration
on:
  push: {branches: [main]}
  pull_request: {}
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker-registry.tools.wmflabs.org/toolforge-php82-sssd-base
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install the testing dependencies
        run: |
          ./composer.phar self-update
          ./composer.phar install

      - name: PHP Lint
        run: |
          ./vendor/bin/phplint --exclude=vendor/

      - name: PHP Code Sniff
        run: |
          ./vendor/bin/phpcs --standard=PSR12 --ignore=vendor/ .
