name: CI
on: {pull_request: {}}
concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
  packages: write
  issues: write
jobs:
  jobs:
    strategy:
      fail-fast: false
      matrix:
        target: [phplint, phpcs]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Save/restore composer cache directory dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: PHP Lint
        run: |
          composer exec phplint -- --exclude=vendor/
        if: matrix.target == 'phplint'

      - name: PHP Code Sniff
        run: |
          composer exec phpcs -- --standard=PSR12 --ignore=vendor/ .
        if: matrix.target == 'phpcs'
