name: Deploy Tagged Release
on:
  release:
    types:
      - released
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
jobs:
  update-components:
    runs-on: ubuntu-latest
    steps:
      - uses: cluebotng/ci-update-component-ref@main
        with:
          tool: '*'
          repository: 'https://github.com/cluebotng/bot.git'
          ref: '${{ inputs.ref || github.ref }}'
          gh_app_key: '${{ secrets.CI_COMPONENT_CONFIGS_APP_KEY }}'
