name: Create Release For Tag
on: { push: { tags: [ 'v*' ] } }
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create GitHub release
        uses: infrabits/ci-create-missing-release@155de6b03975540178a7223ff95c8ae5594bfc68 # main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag: '${{ github.ref }}'

  deploy:
    needs: [create-release]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
